# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "casinocardtracker"
private_key_id = "5d9e5ec5a3df0716dcfaa31d09415dac01aeecfb"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6hMzFgchLlTc4
4eqPbv3W38YnOTb1RUXCBVM/fPmgIsc2to65Hu/3RS0JHW7Y6nbubSlicbl7uMEZ
BTSm6L9xEL/PKIAB0mRZ2oXSOeliMu570yQbZdM2H97+Hjf+cGga3bOs/YwTx7sL
9X6zqMnfuPta6Lv/XjFzjR7ZjfYqBO9FNlDV2ugDZQJBiPquBGkQbVs8G4u57oDr
dBKGwzcX8FJINpd35UTmlZGg/8Twuajf+soRxv3yy0I9VTxNxwT41tlMNkLT8kod
GmElCzrmJF+YIBW6euGLkigOl4tgOQZtFvxOtzE1XubRQaeB+O9jY+SUCTg7MIgn
zoytHOcrAgMBAAECggEAT+YXefvwe0A+WaWdPzhCkMtnLOI7grHcAhMZ6DZ3EHwV
boChfvebwAboFeF/3HgD3nrwoXUqCa/JOBicx2sopxyPrgQhYaZoynzrmnSoXyKG
OpDmBL6HzcW1VpJHVj18uxWBpHcwjEChBaxyTC/f2nB5bCYKcog9Esy/DF7dtn2O
OvZUAIqhWAN/9VPjfwV2lM1Q69Qpwpr9NN5EtbmcQgT0/rv28J5kB+gztjzm0mK0
MHkO29jwX6ubt+jlLrTdYdRSxNX2xycZGf2ztTuBa20KiBr3mWIb5svRSv6igL0B
/CUyMhmsFXG9YrjaeFtWHulMm0qxarm6lHt1ps+BMQKBgQD07YIoAVzuXQM1Lb14
lpiL1LtsZy4I/Id25oz6H4NlKWEKK7GiBYmOKiCg93KmlPPqEjopwf0qOmptfnLR
JL7k1IcLVeSksWfNMXfZYo42B+JUqW5ThfUqh51gEApiRr2hgbOwqi2cgcKFuwHq
eBHPxpcoTMx2t8ErwafB9lg2RQKBgQDC81ZtmIV4y8eMZkjdhq3/PmUn0ERvN/z9
XRX84gohA1uNA/stZOMHvpalgGIyMG0bEycujlhL5l+YsaNvOxrMykHwRk1H3H3m
2iyb+gKxratGB5yDvQ0P4OyqKyk5OisIezK50myZiugFWRZYvVNEgTYwbXg0KOS+
cSX8+Vx2rwKBgQDrg36GTVk480NkXUk1rUmeG77lLAn+JiV0VZj14luMaM+g4gb6
zuxIQYYCgi5CtDQevcwj3x86/dTc2Jw7M2RD0YDRi5RCMTyo+IpQBA7PMaGW2xz1
P3hRnvnbJ1F00qUBqiBJHjqhpbyQrxPWjAJEkqdC3yY0edlL4/kV73U/KQKBgBqU
IHlqrO/OIJOUsmR5YymEcTgfXeUn5fcJBOFoU+cyVP4Bx/Hlakp5AoLn4PtkvMtP
Li1bvNAERY5E0bptfXbkMF84xnqApi2eGyzcxhdBTTOMABu535kFml6M6d7iflF2
snDBLos0c/OetLw+e6bAUwoBMr0xwhXwyTQXLzMDAoGAbnB8BcYKytvlRawqE/K2
yTahUWPV0yn/l5t70vfMCKTV0lK1c2vfvW+PTj7Kn8btyaL18hCr4HRNLDnjn/b4
QyKjQSi5K0qegstpDm4gNKsUr0D7coWmIb90Pgu+GJIqaGaHF6MiEFuNCKOGsVzD
FyihLRSP8ZW9PUFYtFoCSZY=
-----END PRIVATE KEY-----"""
client_email = "sheets-writer@casinocardtracker.iam.gserviceaccount.com"
client_id = "112021982095920237356"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-writer%40casinocardtracker.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[connections.my_data]
type = "file_system"
path = ".streamlit/data"
